#!/bin/sh
while true; do

  digitalWrite --value 1 --pin P8_9

  sleep 2

  digitalWrite --value 0 --pin P8_16
  digitalWrite --value 0 --pin P8_15
  digitalWrite --value 0 --pin P8_14
  digitalWrite --value 0 --pin P8_13

  digitalWrite --value 0 --pin P8_12
  digitalWrite --value 0 --pin P8_11
  digitalWrite --value 0 --pin P8_10
  digitalWrite --value 0 --pin P8_9


  sleep 2
done


